spring.application.name=dio.spring.security.jwt
security.config.prefix=Bearer
security.config.key=ESSA_E_UMA_CHAVE_MUITO_SEGURA_COM_MAIS_DE_32_CARACTERES_PARA_O_JWT
security.config.expiration=3600000

##H2 Database Connection Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.show-sql: true



spring.h2.console.enabled=true
spring.h2.console.path=/h2-console